// Generated by CoffeeScript 1.3.3
(function() {
  var Vec2;

  Vec2 = (function() {

    function Vec2(x, y) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
    }

    Vec2.prototype.clone = function() {
      return new Vec2(this.x, this.y);
    };

    Vec2.prototype.plus = function(other) {
      return new Vec2(this.x + other.x, this.y + other.y);
    };

    Vec2.prototype.minus = function(other) {
      return new Vec2(this.x - other.x, this.y - other.y);
    };

    Vec2.prototype.lengthSquared = function() {
      return this.x * this.x + this.y * this.y;
    };

    Vec2.prototype.length = function() {
      return Math.sqrt(this.lengthSquared());
    };

    Vec2.prototype.direction = function() {
      return Math.atan2(this.y, this.x);
    };

    Vec2.prototype.scaleBy = function(scale) {
      return new Vec2(this.x * scale, this.y * scale);
    };

    Vec2.prototype.clamp = function(maxLength) {
      if (this.lengthSquared() <= maxLength * maxLength) {
        return this.clone();
      } else {
        return this.scaleBy(maxLength / this.length());
      }
    };

    Vec2.prototype.isZero = function() {
      return this.x === 0 && this.y === 0;
    };

    Vec2.prototype.normal = function() {
      return this.scaleBy(1 / this.length());
    };

    return Vec2;

  })();

  window.Vec2 = Vec2;

}).call(this);
