// Generated by CoffeeScript 1.3.3
(function() {

  window.addSettingsPanel = function(settings) {
    var $drawBoundingSphere, $invMass, $maxForce, $maxSpeed, $seeker, $settings, option, _i, _len, _ref;
    $settings = $('#settings');
    $drawBoundingSphere = $('<input type="checkbox">');
    $drawBoundingSphere.change(function() {
      return settings.drawBoundingSphere = $(this).is(':checked');
    });
    $settings.append($drawBoundingSphere).append('Draw bounding sphere<br/>');
    $invMass = $('<input type="range" min="-1" max="2" step="0.25" value="1">');
    $invMass.change(function() {
      return settings.forEntity.invMass = Math.pow(10, $(this).val());
    });
    $settings.append('Inverse mass: ').append($invMass).append('<br/>');
    $maxSpeed = $('<input type="range" min="50" max="400" step="50" value="150">');
    $maxSpeed.change(function() {
      return settings.forEntity.maxSpeed = $(this).val();
    });
    $settings.append('Max speed: ').append($maxSpeed).append('<br/>');
    $maxForce = $('<input type="range" min="10" max="150" step="10" value="50">');
    $maxForce.change(function() {
      return settings.forSteering.maxForce = $(this).val();
    });
    $settings.append('Max force: ').append($maxForce).append('<br/>');
    $seeker = $('<select></select>');
    _ref = ['Seek', 'Arrive'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      option = _ref[_i];
      $seeker.append("<option value\"" + option + "\">" + option + "</option>");
    }
    $seeker.change(function() {
      return settings.steerer = (function() {
        switch ($(this).val()) {
          case 'Seek':
            return new Seeker(settings);
          case 'Arrive':
            return new Arriver(settings);
        }
      }).call(this);
    });
    return $settings.append('Steering: ').append($seeker).append('<br/>');
  };

}).call(this);
