// Generated by CoffeeScript 1.3.3
(function() {
  var Steerer;

  Steerer = (function() {

    function Steerer(game, entity, maxForce) {
      this.game = game;
      this.entity = entity;
      this.maxForce = maxForce;
      this.isOn = {
        seek: false,
        arrive: true
      };
    }

    Steerer.prototype.force = function() {
      var desiredVelocity, distance, force, speed, targetPos, toTarget;
      force = new Vec2;
      targetPos = this.game.mousePos;
      toTarget = targetPos.minus(this.entity.pos);
      if (this.isOn["seek"]) {
        desiredVelocity = toTarget.normal().scaleBy(this.entity.maxSpeed);
        force = desiredVelocity.minus(this.entity.vel);
      }
      if (this.isOn["arrive"]) {
        distance = toTarget.length();
        if (distance > 0) {
          speed = Math.min(this.entity.maxSpeed, distance);
          desiredVelocity = toTarget.normal().scaleBy(speed);
          force = desiredVelocity.minus(this.entity.vel);
        }
      }
      return force.clamp(this.maxForce);
    };

    return Steerer;

  })();

  window.Steerer = Steerer;

}).call(this);
