// Generated by CoffeeScript 1.3.3
(function() {
  var Boid, Canvas, canvas, vector,
    __slice = [].slice;

  vector = {
    add: function() {
      var dimension, result, sum, v, vs, _i, _j, _len, _ref;
      vs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      result = [];
      for (dimension = _i = 0, _ref = vs[0].length; 0 <= _ref ? _i < _ref : _i > _ref; dimension = 0 <= _ref ? ++_i : --_i) {
        sum = 0;
        for (_j = 0, _len = vs.length; _j < _len; _j++) {
          v = vs[_j];
          sum += v[dimension];
        }
        result.push(v);
      }
      return result;
    }
  };

  ({
    distanceSquared: function(v1, v2) {
      var difference;
      difference = vector.subtract(v1, v2);
      return difference.reduce(function(sum, x) {
        return sum + x * x;
      });
    },
    subtract: function(v1, v2) {
      var dimension, result, _i, _ref;
      result = [];
      for (dimension = _i = 0, _ref = v1.length; 0 <= _ref ? _i < _ref : _i > _ref; dimension = 0 <= _ref ? ++_i : --_i) {
        result.push(v1[dimension] - v2[dimension]);
      }
      return result;
    },
    scale: function(v, scale) {
      return v.map(function(x) {
        return x * scale;
      });
    }
  });

  Canvas = (function() {

    function Canvas(id) {
      this.el = document.getElementById(id);
      this.width = parseInt(this.el.getAttribute("width"));
      this.height = parseInt(this.el.getAttribute("height"));
      this.context = this.el.getContext("2d");
      this.clearColor = "black";
    }

    Canvas.prototype.drawRect = function(x, y, width, height, color) {
      this.context.fillStyle = color;
      return this.context.fillRect(x, y, width, height);
    };

    Canvas.prototype.clear = function() {
      return this.drawRect(0, 0, this.width, this.height, this.clearColor);
    };

    return Canvas;

  })();

  Boid = (function() {

    function Boid(pos) {
      this.position = pos;
      this.velocity = [5 + Math.random() * 5, 5 + Math.random() * 5];
    }

    Boid.prototype.update = function() {
      var boid, c1, difference, inverseFlockSize, v1, v2, v3, _i, _len, _ref;
      inverseFlockSize = 1.0 / (this.flock.length - 1);
      c1 = [0, 0];
      v2 = [0, 0];
      v3 = [0, 0];
      _ref = this.flock;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        boid = _ref[_i];
        if (!(boid !== this)) {
          continue;
        }
        c1 = vector.add(c1, boid.position);
        if (vector.distanceSquared(this.position, boid.position) < 250) {
          v2 = vector.subtract(v2, vector.subtract(position.position, this.position));
        }
        v3 = vector.add(v3, boid.velocity);
      }
      c1 = vector.scale(v1, inverseFlockSize);
      difference = vector.subtract(c1, this.position);
      v1 = vector.scale(difference, 0.1);
      v3 = vector.scaleBy(v3, inverseFlockSize);
      v3 = vector.scaleBy(vector.subtract(v3, this.velocity), 0.125);
      this.velocity = vector.add(this.velocity, v1, v2, v3);
      return this.position = vector.add(this.position, this.velocity);
    };

    return Boid;

  })();

  canvas = new Canvas("boids");

  canvas.clearColor = "#202638";

  canvas.clear();

}).call(this);
