// Generated by CoffeeScript 1.3.3
(function() {
  var Canvas, canvas;

  Canvas = (function() {

    function Canvas(id) {
      this.el = document.getElementById(id);
      this.width = parseInt(this.el.getAttribute("width"));
      this.height = parseInt(this.el.getAttribute("height"));
      this.context = this.el.getContext("2d");
      this.clearColor = "black";
    }

    Canvas.prototype.drawRect = function(x, y, width, height, color) {
      this.context.fillStyle = color;
      return this.context.fillRect(x, y, width, height);
    };

    Canvas.prototype.clear = function() {
      return this.drawRect(0, 0, this.width, this.height, this.clearColor);
    };

    return Canvas;

  })();

  canvas = new Canvas("boids");

  canvas.clear();

}).call(this);
